
import React, { useState, useEffect, useRef } from 'react';
import { 
  Gamepad2, Send, Bot, User, Ghost, ScrollText, HelpCircle, 
  RefreshCcw, Smile, BookOpen, Clock, Heart, Trophy, Play, 
  CaseUpper, CheckCircle, XCircle, UserCheck, Search, Lightbulb
} from 'lucide-react';
import { 
  sendChatToProxy, 
  generateEmojiPuzzle, 
  generateWordPuzzle,
  generateTwoTruthsPuzzle,
  generateRiddlePuzzle
} from '../../services/geminiService';
import { ChatMessage, LoadingState, EmojiPuzzle, WordPuzzle, TwoTruthsPuzzle, RiddlePuzzle } from '../../types';

interface GameMode {
  id: string;
  name: string;
  description: string;
  icon: any;
  systemPrompt: string;
  initialMessage: string;
  color: string;
}

const GAMES: GameMode[] = [
  {
    id: 'adventure',
    name: 'Text Adventure',
    description: 'Explore a fantasy world where your choices shape the story.',
    icon: ScrollText,
    color: 'emerald',
    systemPrompt: "You are the Dungeon Master for a text-based fantasy adventure game. Guide the player through a mysterious world. Describe the environment vividly. Offer choices but allow creative inputs. Keep responses concise (under 100 words) to maintain pace. Start by introducing the setting.",
    initialMessage: "Welcome, traveler. Your journey begins at the edge of the Whispering Woods. To your left is a dark cave, and to your right, a winding path towards the mountains. What do you do?"
  },
  {
    id: 'mystery',
    name: 'Murder Mystery',
    description: 'Interrogate suspects and solve the crime.',
    icon: Ghost,
    color: 'purple',
    systemPrompt: "You are a narrator for a noir murder mystery game. The user is the detective. Present a crime scene, a list of 3 suspects with secrets, and clues. The user must ask questions to solve it. When they accuse correctly, congratulate them. Start by setting the scene.",
    initialMessage: "Detective, we have a body in the library. Mr. Higgins was found dead. The suspects are the Maid, the Butler, and the Nephew. Who do you want to question first?"
  },
  {
    id: 'trivia',
    name: 'Trivia Challenge',
    description: 'Test your knowledge against an infinite quiz master.',
    icon: HelpCircle,
    color: 'amber',
    systemPrompt: "You are a fun, energetic Trivia Host. Ask the user general knowledge questions one by one. Wait for their answer. If they are right, cheer and give points. If wrong, explain the answer. Then ask the next question. Keep it fast-paced.",
    initialMessage: "Welcome to the AI Trivia Challenge! I'm ready when you are. Type 'Start' to get your first question!"
  },
  {
    id: 'emoji',
    name: 'Emoji Translator',
    description: 'Translate text to emojis or decipher emoji sentences.',
    icon: Smile,
    color: 'pink',
    systemPrompt: "You are an Emoji Translator Bot. You have two modes: 1. Text-to-Emoji: Convert the user's sentence into a string of emojis that represent the meaning. 2. Emoji-to-Text: Translate the user's emoji string into a funny or literal text interpretation. Ask the user which mode they want to play first.",
    initialMessage: "👋🌍! I speak fluent Emoji. Want me to translate your text into emojis, or do you want to send me emojis to decipher?"
  },
  {
    id: 'word',
    name: 'Word Wizard',
    description: 'Master spelling by picking the correct word from tricky options.',
    icon: CaseUpper,
    color: 'cyan',
    systemPrompt: "You are a Spelling Bee Master. Challenge the user with difficult words. Give them the definition and ask them to spell it, or provide multiple choice options. Celebrate their victory if they get it right.",
    initialMessage: "Welcome to Word Wizard! I'm here to test your vocabulary and spelling skills. Type 'Ready' to begin a spelling duel!"
  },
  {
    id: 'bible',
    name: 'Bible Companion',
    description: 'Trivia, roleplay, and study helper for biblical texts.',
    icon: BookOpen,
    color: 'blue',
    systemPrompt: "You are a warm, knowledgeable Bible Companion. You can facilitate Bible Trivia, explain specific verses in simple terms, or roleplay as a biblical character for an immersive learning experience. Ask the user what they would like to do today.",
    initialMessage: "Greetings! I am here to explore the scriptures with you. We can play Bible Trivia, explore the meaning of a verse, or I can step into the shoes of a biblical figure for a chat. What would you like to do?"
  },
  {
    id: 'truths',
    name: 'Two Truths & A Lie',
    description: 'Spot the fake statement generated by AI.',
    icon: UserCheck,
    color: 'rose',
    systemPrompt: "You are playing Two Truths and a Lie. Generate 3 statements about a topic, where 2 are true and 1 is false. Ask the user to guess the lie.",
    initialMessage: "Ready to play? I'll present three statements. You have to catch me lying!"
  },
  {
    id: 'riddle',
    name: 'Riddle Realm',
    description: 'Solve clever rhymes and puzzles generated by Gemini.',
    icon: Lightbulb,
    color: 'violet',
    systemPrompt: "You are a Riddle Master. Generate difficult but solvable riddles for the user. If they struggle, offer a subtle hint. If they give up, reveal the answer and explain it.",
    initialMessage: "I possess no voice, yet I speak to all. I have leaves, but I am not a tree. What am I? (Type your answer!)"
  }
];

// --- Emoji Challenge Sub-Component ---
const EmojiChallenge: React.FC<{ onExit: () => void }> = ({ onExit }) => {
  const [puzzle, setPuzzle] = useState<EmojiPuzzle | null>(null);
  const [guess, setGuess] = useState('');
  const [attempts, setAttempts] = useState(3);
  const [timeLeft, setTimeLeft] = useState(60);
  const [gameState, setGameState] = useState<'loading' | 'playing' | 'won' | 'lost'>('loading');
  const [score, setScore] = useState(0);

  useEffect(() => {
    loadPuzzle();
  }, []);

  useEffect(() => {
    let timer: any;
    if (gameState === 'playing' && timeLeft > 0) {
      timer = setInterval(() => {
        setTimeLeft((prev) => prev - 1);
      }, 1000);
    } else if (timeLeft === 0 && gameState === 'playing') {
      setGameState('lost');
    }
    return () => clearInterval(timer);
  }, [gameState, timeLeft]);

  const loadPuzzle = async () => {
    setGameState('loading');
    setGuess('');
    setAttempts(3);
    setTimeLeft(60);
    try {
      const newPuzzle = await generateEmojiPuzzle();
      setPuzzle(newPuzzle);
      setGameState('playing');
    } catch (e) {
      console.error(e);
      // Retry once or handle error
    }
  };

  const checkGuess = () => {
    if (!puzzle || !guess.trim()) return;
    
    // Normalize strings for comparison (remove punctuation, lowercase)
    const normalize = (str: string) => str.toLowerCase().replace(/[^a-z0-9]/g, '');
    const userGuess = normalize(guess);
    const correctAnswer = normalize(puzzle.answer);

    if (userGuess === correctAnswer || (correctAnswer.includes(userGuess) && userGuess.length > 3)) {
      setScore(s => s + 10 + (attempts * 2));
      setGameState('won');
    } else {
      setAttempts(prev => {
        const newAttempts = prev - 1;
        if (newAttempts <= 0) setGameState('lost');
        return newAttempts;
      });
      setGuess('');
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 shadow-2xl relative">
      {/* HUD */}
      <div className="bg-slate-950 p-4 border-b border-slate-800 flex justify-between items-center">
        <div className="flex items-center gap-4">
          <button onClick={onExit} className="text-slate-500 hover:text-white flex items-center gap-1">
             <XCircle className="w-5 h-5"/> EXIT
          </button>
          <div className="flex items-center gap-2 text-yellow-400 font-bold">
            <Trophy className="w-5 h-5" />
            <span>Score: {score}</span>
          </div>
          <div className="flex items-center gap-1">
             {[...Array(3)].map((_, i) => (
               <Heart key={i} className={`w-5 h-5 ${i < attempts ? 'text-red-500 fill-current' : 'text-slate-700'}`} />
             ))}
          </div>
        </div>
        <div className="flex items-center gap-2 font-mono text-slate-300 bg-slate-800 px-3 py-1 rounded-lg">
          <Clock className="w-4 h-4" />
          <span className={`${timeLeft < 10 ? 'text-red-500 animate-pulse' : ''}`}>{timeLeft}s</span>
        </div>
      </div>

      {/* Progress Bar */}
      <div className="h-1 bg-slate-800 w-full">
        <div 
          className="h-full bg-gradient-to-r from-pink-500 to-purple-500 transition-all duration-1000 ease-linear"
          style={{ width: `${(timeLeft / 60) * 100}%` }}
        ></div>
      </div>

      {/* Game Area */}
      <div className="flex-1 flex flex-col items-center justify-center p-8 space-y-8 text-center">
        {gameState === 'loading' && (
          <div className="animate-bounce">
            <span className="text-6xl">🎲</span>
            <p className="mt-4 text-slate-400">Loading Puzzle...</p>
          </div>
        )}

        {puzzle && gameState !== 'loading' && (
          <>
            <div className="space-y-2">
              <span className="text-xs font-bold uppercase tracking-widest text-pink-500 bg-pink-500/10 px-3 py-1 rounded-full">
                {puzzle.category}
              </span>
              <div className="text-6xl md:text-8xl py-4 animate-pulse-slow">
                {puzzle.emojis}
              </div>
            </div>

            {gameState === 'playing' ? (
              <div className="w-full max-w-md space-y-4">
                <input
                  type="text"
                  value={guess}
                  onChange={(e) => setGuess(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && checkGuess()}
                  placeholder="Type your guess here..."
                  className="w-full bg-slate-800 border-2 border-slate-700 focus:border-pink-500 rounded-xl px-4 py-4 text-center text-xl text-white placeholder-slate-600 focus:outline-none transition-all"
                  autoFocus
                />
                <button
                  onClick={checkGuess}
                  className="w-full bg-pink-600 hover:bg-pink-700 text-white font-bold py-3 rounded-xl transition-colors"
                >
                  Submit Guess
                </button>
              </div>
            ) : (
              <div className="space-y-6 animate-fade-in-up">
                <div className="space-y-2">
                  <h3 className={`text-3xl font-bold ${gameState === 'won' ? 'text-green-400' : 'text-red-400'}`}>
                    {gameState === 'won' ? 'Correct!' : 'Time\'s Up!'}
                  </h3>
                  <p className="text-xl text-slate-300">
                    The answer was: <span className="text-white font-bold underline decoration-pink-500">{puzzle.answer}</span>
                  </p>
                </div>
                <button
                  onClick={loadPuzzle}
                  className="bg-white text-slate-900 hover:bg-slate-200 font-bold px-8 py-3 rounded-xl flex items-center gap-2 mx-auto transition-colors"
                >
                  <Play className="w-5 h-5 fill-current" />
                  Next Puzzle
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

// --- Word Wizard Challenge Sub-Component ---
const WordChallenge: React.FC<{ onExit: () => void }> = ({ onExit }) => {
  const [puzzle, setPuzzle] = useState<WordPuzzle | null>(null);
  const [options, setOptions] = useState<string[]>([]);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [gameState, setGameState] = useState<'loading' | 'playing' | 'result'>('loading');
  const [score, setScore] = useState(0);

  useEffect(() => {
    loadPuzzle();
  }, []);

  const loadPuzzle = async () => {
    setGameState('loading');
    setSelectedOption(null);
    try {
      const newPuzzle = await generateWordPuzzle();
      setPuzzle(newPuzzle);
      // Shuffle options
      const allOptions = [newPuzzle.word, ...newPuzzle.distractors].sort(() => Math.random() - 0.5);
      setOptions(allOptions);
      setGameState('playing');
    } catch (e) {
      console.error(e);
    }
  };

  const handleSelect = (option: string) => {
    if (gameState !== 'playing') return;
    setSelectedOption(option);
    setGameState('result');
    if (option === puzzle?.word) {
      setScore(s => s + 10);
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 shadow-2xl relative">
      {/* Header */}
      <div className="bg-slate-950 p-4 border-b border-slate-800 flex justify-between items-center">
        <div className="flex items-center gap-4">
            <button onClick={onExit} className="text-slate-500 hover:text-white flex items-center gap-1">
                <XCircle className="w-5 h-5"/> EXIT
            </button>
            <h3 className="font-bold text-white flex items-center gap-2">
            <CaseUpper className="w-5 h-5 text-cyan-500" />
            Word Wizard
            </h3>
        </div>
        <div className="flex items-center gap-2 text-cyan-400 font-bold bg-slate-900 px-3 py-1 rounded-full border border-slate-800">
          <Trophy className="w-4 h-4" />
          <span>Score: {score}</span>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex flex-col items-center justify-center p-8 space-y-10">
        {gameState === 'loading' ? (
           <div className="text-center animate-pulse">
             <div className="w-16 h-16 bg-cyan-500/20 text-cyan-500 rounded-full flex items-center justify-center mx-auto mb-4">
               <RefreshCcw className="w-8 h-8 animate-spin" />
             </div>
             <p className="text-slate-400">Summoning a tricky word...</p>
           </div>
        ) : puzzle && (
          <>
            <div className="text-center space-y-4 max-w-2xl">
              <span className="text-xs font-bold uppercase tracking-widest text-slate-500">Definition</span>
              <p className="text-2xl md:text-3xl font-medium text-white leading-relaxed">
                "{puzzle.definition}"
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 w-full max-w-3xl">
              {options.map((option, idx) => {
                let btnClass = "bg-slate-800 hover:bg-slate-700 border-slate-700 text-slate-300";
                
                if (gameState === 'result') {
                  if (option === puzzle.word) {
                    btnClass = "bg-green-600 border-green-500 text-white shadow-lg shadow-green-900/20"; // Correct answer always green
                  } else if (option === selectedOption && option !== puzzle.word) {
                    btnClass = "bg-red-600 border-red-500 text-white opacity-50"; // Wrong selection red
                  } else {
                    btnClass = "bg-slate-900 border-slate-800 text-slate-600 opacity-50"; // Others dimmed
                  }
                }

                return (
                  <button
                    key={idx}
                    onClick={() => handleSelect(option)}
                    disabled={gameState === 'result'}
                    className={`
                      relative p-6 rounded-xl border-2 text-lg font-bold transition-all duration-300
                      flex flex-col items-center justify-center gap-2
                      ${btnClass}
                      ${gameState === 'playing' ? 'hover:-translate-y-1 hover:shadow-xl' : ''}
                    `}
                  >
                    {option}
                    {gameState === 'result' && option === puzzle.word && (
                       <CheckCircle className="w-5 h-5 absolute top-3 right-3 text-white/50" />
                    )}
                    {gameState === 'result' && option === selectedOption && option !== puzzle.word && (
                       <XCircle className="w-5 h-5 absolute top-3 right-3 text-white/50" />
                    )}
                  </button>
                );
              })}
            </div>

            {gameState === 'result' && (
              <div className="animate-fade-in-up">
                 <button
                  onClick={loadPuzzle}
                  className="bg-cyan-600 hover:bg-cyan-700 text-white font-bold px-8 py-3 rounded-xl flex items-center gap-2 transition-all shadow-lg shadow-cyan-900/20"
                >
                  <Play className="w-5 h-5 fill-current" />
                  Next Word
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

// --- Two Truths Challenge Sub-Component ---
const TwoTruthsChallenge: React.FC<{ onExit: () => void }> = ({ onExit }) => {
  const [puzzle, setPuzzle] = useState<TwoTruthsPuzzle | null>(null);
  const [gameState, setGameState] = useState<'loading' | 'playing' | 'result'>('loading');
  const [score, setScore] = useState(0);
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);

  useEffect(() => {
    loadPuzzle();
  }, []);

  const loadPuzzle = async () => {
    setGameState('loading');
    setSelectedIndex(null);
    try {
      const newPuzzle = await generateTwoTruthsPuzzle();
      setPuzzle(newPuzzle);
      setGameState('playing');
    } catch (e) {
      console.error(e);
    }
  };

  const handleGuess = (index: number) => {
    if (gameState !== 'playing' || !puzzle) return;
    setSelectedIndex(index);
    setGameState('result');
    if (puzzle.statements[index].isTruth === false) {
      // The user correctly identified the lie (which is false)
      setScore(s => s + 10);
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 shadow-2xl relative">
      <div className="bg-slate-950 p-4 border-b border-slate-800 flex justify-between items-center">
        <div className="flex items-center gap-4">
            <button onClick={onExit} className="text-slate-500 hover:text-white flex items-center gap-1">
                <XCircle className="w-5 h-5"/> EXIT
            </button>
            <h3 className="font-bold text-white flex items-center gap-2">
            <UserCheck className="w-5 h-5 text-rose-500" />
            Two Truths & A Lie
            </h3>
        </div>
        <div className="flex items-center gap-2 text-rose-400 font-bold bg-slate-900 px-3 py-1 rounded-full border border-slate-800">
          <Trophy className="w-4 h-4" />
          <span>Score: {score}</span>
        </div>
      </div>

      <div className="flex-1 flex flex-col items-center justify-center p-8 space-y-8">
        {gameState === 'loading' ? (
           <div className="text-center animate-pulse">
             <div className="w-16 h-16 bg-rose-500/20 text-rose-500 rounded-full flex items-center justify-center mx-auto mb-4">
               <RefreshCcw className="w-8 h-8 animate-spin" />
             </div>
             <p className="text-slate-400">Fabricating truths and lies...</p>
           </div>
        ) : puzzle && (
          <>
             <div className="text-center space-y-2">
               <span className="text-xs font-bold uppercase tracking-widest text-slate-500">Topic</span>
               <h2 className="text-3xl font-bold text-white">{puzzle.topic}</h2>
               <p className="text-slate-400">Which one is the lie?</p>
             </div>

             <div className="grid grid-cols-1 gap-4 w-full max-w-2xl">
                {puzzle.statements.map((stmt, idx) => {
                   let btnClass = "bg-slate-800 hover:bg-slate-700 border-slate-700 text-slate-200";
                   
                   if (gameState === 'result') {
                     if (!stmt.isTruth) {
                        // This was the lie
                        btnClass = "bg-green-600 border-green-500 text-white"; 
                     } else if (idx === selectedIndex && stmt.isTruth) {
                        // You picked truth (wrong)
                        btnClass = "bg-red-600 border-red-500 text-white";
                     } else {
                        btnClass = "bg-slate-900 text-slate-600 border-slate-800";
                     }
                   }

                   return (
                     <button
                       key={idx}
                       onClick={() => handleGuess(idx)}
                       disabled={gameState === 'result'}
                       className={`
                         p-5 rounded-xl border text-left text-lg font-medium transition-all
                         flex items-center justify-between group
                         ${btnClass}
                         ${gameState === 'playing' ? 'hover:scale-[1.02] hover:shadow-lg' : ''}
                       `}
                     >
                       <span>{stmt.text}</span>
                       {gameState === 'result' && !stmt.isTruth && <CheckCircle className="w-5 h-5" />}
                       {gameState === 'result' && stmt.isTruth && idx === selectedIndex && <XCircle className="w-5 h-5" />}
                     </button>
                   );
                })}
             </div>

             {gameState === 'result' && (
               <div className="text-center space-y-6 animate-fade-in-up max-w-2xl">
                 <div className="bg-slate-950/50 p-4 rounded-xl border border-slate-800">
                    <p className="text-slate-300 italic">"{puzzle.explanation}"</p>
                 </div>
                 <button
                  onClick={loadPuzzle}
                  className="bg-rose-600 hover:bg-rose-700 text-white font-bold px-8 py-3 rounded-xl flex items-center gap-2 mx-auto transition-colors"
                >
                  <Play className="w-5 h-5 fill-current" />
                  Next Round
                </button>
               </div>
             )}
          </>
        )}
      </div>
    </div>
  );
};

// --- Riddle Challenge Sub-Component ---
const RiddleChallenge: React.FC<{ onExit: () => void }> = ({ onExit }) => {
  const [puzzle, setPuzzle] = useState<RiddlePuzzle | null>(null);
  const [guess, setGuess] = useState('');
  const [showHint, setShowHint] = useState(false);
  const [gameState, setGameState] = useState<'loading' | 'playing' | 'revealed' | 'won'>('loading');
  const [score, setScore] = useState(0);

  useEffect(() => {
    loadPuzzle();
  }, []);

  const loadPuzzle = async () => {
    setGameState('loading');
    setGuess('');
    setShowHint(false);
    try {
      const newPuzzle = await generateRiddlePuzzle();
      setPuzzle(newPuzzle);
      setGameState('playing');
    } catch (e) {
      console.error(e);
    }
  };

  const checkGuess = () => {
    if (!puzzle || !guess.trim()) return;
    
    // Normalize strings for lenient matching
    const normalize = (str: string) => str.toLowerCase().replace(/[^a-z0-9]/g, '');
    const userGuess = normalize(guess);
    const correctAnswer = normalize(puzzle.answer);

    if (userGuess === correctAnswer || correctAnswer.includes(userGuess)) {
      const points = showHint ? 5 : 10;
      setScore(s => s + points);
      setGameState('won');
    } else {
      // Just shake or notify wrong (simplified here)
      alert("Not quite! Try again or use a hint.");
    }
  };

  const handleReveal = () => {
    setGameState('revealed');
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 shadow-2xl relative">
      <div className="bg-slate-950 p-4 border-b border-slate-800 flex justify-between items-center">
        <div className="flex items-center gap-4">
            <button onClick={onExit} className="text-slate-500 hover:text-white flex items-center gap-1">
                <XCircle className="w-5 h-5"/> EXIT
            </button>
            <h3 className="font-bold text-white flex items-center gap-2">
            <Lightbulb className="w-5 h-5 text-violet-500" />
            Riddle Realm
            </h3>
        </div>
        <div className="flex items-center gap-2 text-violet-400 font-bold bg-slate-900 px-3 py-1 rounded-full border border-slate-800">
          <Trophy className="w-4 h-4" />
          <span>Score: {score}</span>
        </div>
      </div>

      <div className="flex-1 flex flex-col items-center justify-center p-8 space-y-8">
        {gameState === 'loading' ? (
           <div className="text-center animate-pulse">
             <div className="w-16 h-16 bg-violet-500/20 text-violet-500 rounded-full flex items-center justify-center mx-auto mb-4">
               <RefreshCcw className="w-8 h-8 animate-spin" />
             </div>
             <p className="text-slate-400">Crafting a mystery...</p>
           </div>
        ) : puzzle && (
          <>
             <div className="text-center space-y-2">
                <span className={`text-xs font-bold uppercase tracking-widest px-2 py-1 rounded ${
                   puzzle.difficulty === 'Hard' ? 'bg-red-500/20 text-red-400' : 'bg-green-500/20 text-green-400'
                }`}>
                   {puzzle.difficulty}
                </span>
                <p className="text-2xl md:text-3xl font-medium text-white leading-relaxed max-w-2xl mx-auto italic">
                  "{puzzle.question}"
                </p>
             </div>

             {gameState === 'playing' ? (
                <div className="w-full max-w-md space-y-4">
                   <div className="relative">
                      <input
                        type="text"
                        value={guess}
                        onChange={(e) => setGuess(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && checkGuess()}
                        placeholder="What am I?"
                        className="w-full bg-slate-950 border border-slate-700 rounded-xl px-4 py-4 text-center text-white focus:border-violet-500 focus:outline-none"
                        autoFocus
                      />
                      <button 
                         onClick={checkGuess}
                         className="absolute right-2 top-2 bottom-2 bg-violet-600 hover:bg-violet-700 text-white px-4 rounded-lg font-bold transition-colors"
                      >
                         Guess
                      </button>
                   </div>
                   
                   <div className="flex justify-center gap-4">
                      <button
                        onClick={() => setShowHint(true)}
                        disabled={showHint}
                        className={`text-sm flex items-center gap-1 ${showHint ? 'text-slate-500' : 'text-yellow-500 hover:text-yellow-400'}`}
                      >
                         <Lightbulb className="w-4 h-4" />
                         {showHint ? puzzle.hint : "Need a Hint?"}
                      </button>
                      <button
                        onClick={handleReveal}
                        className="text-sm text-slate-500 hover:text-red-400"
                      >
                         Give Up
                      </button>
                   </div>
                </div>
             ) : (
                <div className="text-center space-y-6 animate-fade-in-up">
                   <h3 className={`text-2xl font-bold ${gameState === 'won' ? 'text-green-400' : 'text-slate-300'}`}>
                      {gameState === 'won' ? 'Brilliant!' : 'The answer was:'}
                   </h3>
                   <div className="bg-slate-950/50 px-8 py-4 rounded-xl border border-slate-800 inline-block">
                      <span className="text-2xl text-white font-bold">{puzzle.answer}</span>
                   </div>
                   <div className="block">
                      <button
                        onClick={loadPuzzle}
                        className="bg-violet-600 hover:bg-violet-700 text-white font-bold px-8 py-3 rounded-xl flex items-center gap-2 mx-auto transition-colors"
                      >
                        <Play className="w-5 h-5 fill-current" />
                        Next Riddle
                      </button>
                   </div>
                </div>
             )}
          </>
        )}
      </div>
    </div>
  );
};

// --- Main Games Tool ---
const GamesTool: React.FC = () => {
  const [activeGame, setActiveGame] = useState<GameMode | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [status, setStatus] = useState<LoadingState>('idle');
  const [subMode, setSubMode] = useState<'chat' | 'challenge'>('chat'); 
  
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const startGame = (game: GameMode) => {
    setActiveGame(game);
    setSubMode('chat'); // Reset submode
    setMessages([{ role: 'model', text: game.initialMessage }]);
  };

  const exitGame = () => {
    setActiveGame(null);
    setMessages([]);
    setSubMode('chat');
  };

  const handleSend = async () => {
    if (!inputValue.trim() || !activeGame || status === 'loading') return;

    const userText = inputValue.trim();
    setInputValue('');
    setStatus('loading');

    const newMessages = [...messages, { role: 'user', text: userText }];
    setMessages(newMessages);

    try {
      const history = newMessages.map(m => ({
        role: m.role,
        parts: [{ text: m.text }]
      }));

      const responseText = await sendChatToProxy(history as any, 'gemini-3-flash-preview', activeGame.systemPrompt);
      const modelText = responseText || "The game master is silent...";
      
      setMessages(prev => [...prev, { role: 'model', text: modelText }]);
      setStatus('idle');
    } catch (error) {
      console.error("Game Error:", error);
      setMessages(prev => [...prev, { role: 'model', text: "Sorry, the game master encountered an error." }]);
      setStatus('error');
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') handleSend();
  };

  // Render specific challenge components based on game ID
  if (activeGame) {
     if (activeGame.id === 'emoji') return <div className="h-[600px]"><EmojiChallenge onExit={exitGame} /></div>;
     if (activeGame.id === 'word') return <div className="h-[600px]"><WordChallenge onExit={exitGame} /></div>;
     if (activeGame.id === 'truths') return <div className="h-[600px]"><TwoTruthsChallenge onExit={exitGame} /></div>;
     if (activeGame.id === 'riddle') return <div className="h-[600px]"><RiddleChallenge onExit={exitGame} /></div>;

     // For text-based games (Adventure, Mystery, Trivia, Bible)
     return (
        <div className="h-[600px] flex flex-col bg-slate-900 rounded-2xl border border-slate-800 shadow-2xl overflow-hidden">
           {/* Header */}
           <div className="p-4 bg-slate-950 border-b border-slate-800 flex justify-between items-center">
              <div className="flex items-center gap-2 text-white font-bold">
                 <activeGame.icon className={`w-5 h-5 text-${activeGame.color}-500`} />
                 {activeGame.name}
              </div>
              <button onClick={exitGame} className="text-xs text-slate-500 hover:text-white uppercase font-bold tracking-wider">
                 Exit Game
              </button>
           </div>

           {/* Chat Area */}
           <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar">
              {messages.map((msg, idx) => (
                 <div key={idx} className={`flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${msg.role === 'user' ? 'bg-slate-700' : `bg-${activeGame.color}-600`}`}>
                       {msg.role === 'user' ? <User className="w-5 h-5 text-slate-300" /> : <Bot className="w-5 h-5 text-white" />}
                    </div>
                    <div className={`rounded-2xl px-5 py-3 text-sm leading-relaxed whitespace-pre-wrap shadow-md max-w-[80%] ${msg.role === 'user' ? 'bg-slate-800 text-slate-100 rounded-tr-none' : 'bg-slate-950/80 border border-slate-800 text-slate-300 rounded-tl-none'}`}>
                       {msg.text}
                    </div>
                 </div>
              ))}
              {status === 'loading' && (
                 <div className="flex gap-4">
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 bg-${activeGame.color}-600`}>
                       <Bot className="w-5 h-5 text-white" />
                    </div>
                    <div className="bg-slate-950/50 border border-slate-800 rounded-2xl rounded-tl-none px-5 py-4 flex items-center gap-2">
                       <div className="w-2 h-2 bg-slate-500 rounded-full animate-bounce"></div>
                       <div className="w-2 h-2 bg-slate-500 rounded-full animate-bounce delay-100"></div>
                       <div className="w-2 h-2 bg-slate-500 rounded-full animate-bounce delay-200"></div>
                    </div>
                 </div>
              )}
              <div ref={messagesEndRef} />
           </div>

           {/* Input */}
           <div className="p-4 bg-slate-950 border-t border-slate-800 flex gap-2">
              <input 
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Type your action or answer..."
                className="flex-1 bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                autoFocus
              />
              <button 
                onClick={handleSend}
                disabled={!inputValue.trim() || status === 'loading'}
                className="bg-blue-600 hover:bg-blue-700 text-white p-3 rounded-xl disabled:opacity-50"
              >
                 <Send className="w-5 h-5" />
              </button>
           </div>
        </div>
     );
  }

  // Dashboard / Menu
  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-fade-in">
       <div className="text-center space-y-2">
         <h2 className="text-3xl font-bold text-slate-900 dark:text-white flex items-center justify-center gap-3">
           <Gamepad2 className="w-8 h-8 text-orange-500" />
           AI Games
         </h2>
         <p className="text-slate-600 dark:text-slate-400">Play infinite AI-generated games.</p>
       </div>

       <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {GAMES.map((game) => (
             <button
               key={game.id}
               onClick={() => startGame(game)}
               className="bg-slate-800 hover:bg-slate-750 border border-slate-700 hover:border-slate-500 p-6 rounded-2xl text-left transition-all hover:-translate-y-1 group relative overflow-hidden"
             >
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 bg-${game.color}-500/10 text-${game.color}-500 group-hover:bg-${game.color}-500 group-hover:text-white transition-colors`}>
                   <game.icon className="w-6 h-6" />
                </div>
                <h3 className="font-bold text-white text-lg mb-1">{game.name}</h3>
                <p className="text-sm text-slate-400 leading-snug">{game.description}</p>
             </button>
          ))}
       </div>
    </div>
  );
};

export default GamesTool;
