import React, { useState, useEffect, useRef } from 'react';
import { 
  Gamepad2, Send, Bot, User, Ghost, ScrollText, HelpCircle, 
  RefreshCcw, Smile, BookOpen, Clock, Heart, Trophy, Play, 
  CaseUpper, CheckCircle, XCircle, UserCheck 
} from 'lucide-react';
import { Chat } from "@google/genai";
import { 
  createChatSession, 
  generateEmojiPuzzle, 
  generateWordPuzzle,
  generateTwoTruthsPuzzle
} from '../../services/geminiService';
import { ChatMessage, LoadingState, EmojiPuzzle, WordPuzzle, TwoTruthsPuzzle } from '../../types';

interface GameMode {
  id: string;
  name: string;
  description: string;
  icon: any;
  systemPrompt: string;
  initialMessage: string;
  color: string;
}

const GAMES: GameMode[] = [
  {
    id: 'adventure',
    name: 'Text Adventure',
    description: 'Explore a fantasy world where your choices shape the story.',
    icon: ScrollText,
    color: 'emerald',
    systemPrompt: "You are the Dungeon Master for a text-based fantasy adventure game. Guide the player through a mysterious world. Describe the environment vividly. Offer choices but allow creative inputs. Keep responses concise (under 100 words) to maintain pace. Start by introducing the setting.",
    initialMessage: "Welcome, traveler. Your journey begins at the edge of the Whispering Woods. To your left is a dark cave, and to your right, a winding path towards the mountains. What do you do?"
  },
  {
    id: 'mystery',
    name: 'Murder Mystery',
    description: 'Interrogate suspects and solve the crime.',
    icon: Ghost,
    color: 'purple',
    systemPrompt: "You are a narrator for a noir murder mystery game. The user is the detective. Present a crime scene, a list of 3 suspects with secrets, and clues. The user must ask questions to solve it. When they accuse correctly, congratulate them. Start by setting the scene.",
    initialMessage: "Detective, we have a body in the library. Mr. Higgins was found dead. The suspects are the Maid, the Butler, and the Nephew. Who do you want to question first?"
  },
  {
    id: 'trivia',
    name: 'Trivia Challenge',
    description: 'Test your knowledge against an infinite quiz master.',
    icon: HelpCircle,
    color: 'amber',
    systemPrompt: "You are a fun, energetic Trivia Host. Ask the user general knowledge questions one by one. Wait for their answer. If they are right, cheer and give points. If wrong, explain the answer. Then ask the next question. Keep it fast-paced.",
    initialMessage: "Welcome to the Nano Trivia Challenge! I'm ready when you are. Type 'Start' to get your first question!"
  },
  {
    id: 'emoji',
    name: 'Emoji Translator',
    description: 'Translate text to emojis or decipher emoji sentences.',
    icon: Smile,
    color: 'pink',
    systemPrompt: "You are an Emoji Translator Bot. You have two modes: 1. Text-to-Emoji: Convert the user's sentence into a string of emojis that represent the meaning. 2. Emoji-to-Text: Translate the user's emoji string into a funny or literal text interpretation. Ask the user which mode they want to play first.",
    initialMessage: "👋🌍! I speak fluent Emoji. Want me to translate your text into emojis, or do you want to send me emojis to decipher?"
  },
  {
    id: 'word',
    name: 'Word Wizard',
    description: 'Master spelling by picking the correct word from tricky options.',
    icon: CaseUpper,
    color: 'cyan',
    systemPrompt: "You are a Spelling Bee Master. Challenge the user with difficult words. Give them the definition and ask them to spell it, or provide multiple choice options. Celebrate their victory if they get it right.",
    initialMessage: "Welcome to Word Wizard! I'm here to test your vocabulary and spelling skills. Type 'Ready' to begin a spelling duel!"
  },
  {
    id: 'bible',
    name: 'Bible Companion',
    description: 'Trivia, roleplay, and study helper for biblical texts.',
    icon: BookOpen,
    color: 'blue',
    systemPrompt: "You are a warm, knowledgeable Bible Companion. You can facilitate Bible Trivia, explain specific verses in simple terms, or roleplay as a biblical character for an immersive learning experience. Ask the user what they would like to do today.",
    initialMessage: "Greetings! I am here to explore the scriptures with you. We can play Bible Trivia, explore the meaning of a verse, or I can step into the shoes of a biblical figure for a chat. What would you like to do?"
  },
  {
    id: 'truths',
    name: 'Two Truths & A Lie',
    description: 'Spot the fake statement generated by AI.',
    icon: UserCheck,
    color: 'rose',
    systemPrompt: "You are playing Two Truths and a Lie. Generate 3 statements about a topic, where 2 are true and 1 is false. Ask the user to guess the lie.",
    initialMessage: "Ready to play? I'll present three statements. You have to catch me lying!"
  }
];

// --- Emoji Challenge Sub-Component ---
const EmojiChallenge: React.FC<{ onExit: () => void }> = ({ onExit }) => {
  const [puzzle, setPuzzle] = useState<EmojiPuzzle | null>(null);
  const [guess, setGuess] = useState('');
  const [attempts, setAttempts] = useState(3);
  const [timeLeft, setTimeLeft] = useState(60);
  const [gameState, setGameState] = useState<'loading' | 'playing' | 'won' | 'lost'>('loading');
  const [score, setScore] = useState(0);

  useEffect(() => {
    loadPuzzle();
  }, []);

  useEffect(() => {
    let timer: any;
    if (gameState === 'playing' && timeLeft > 0) {
      timer = setInterval(() => {
        setTimeLeft((prev) => prev - 1);
      }, 1000);
    } else if (timeLeft === 0 && gameState === 'playing') {
      setGameState('lost');
    }
    return () => clearInterval(timer);
  }, [gameState, timeLeft]);

  const loadPuzzle = async () => {
    setGameState('loading');
    setGuess('');
    setAttempts(3);
    setTimeLeft(60);
    try {
      const newPuzzle = await generateEmojiPuzzle();
      setPuzzle(newPuzzle);
      setGameState('playing');
    } catch (e) {
      console.error(e);
      // Retry once or handle error
    }
  };

  const checkGuess = () => {
    if (!puzzle || !guess.trim()) return;
    
    // Normalize strings for comparison (remove punctuation, lowercase)
    const normalize = (str: string) => str.toLowerCase().replace(/[^a-z0-9]/g, '');
    const userGuess = normalize(guess);
    const correctAnswer = normalize(puzzle.answer);

    if (userGuess === correctAnswer || (correctAnswer.includes(userGuess) && userGuess.length > 3)) {
      setScore(s => s + 10 + (attempts * 2));
      setGameState('won');
    } else {
      setAttempts(prev => {
        const newAttempts = prev - 1;
        if (newAttempts <= 0) setGameState('lost');
        return newAttempts;
      });
      setGuess('');
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 shadow-2xl relative">
      {/* HUD */}
      <div className="bg-slate-950 p-4 border-b border-slate-800 flex justify-between items-center">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 text-yellow-400 font-bold">
            <Trophy className="w-5 h-5" />
            <span>Score: {score}</span>
          </div>
          <div className="flex items-center gap-1">
             {[...Array(3)].map((_, i) => (
               <Heart key={i} className={`w-5 h-5 ${i < attempts ? 'text-red-500 fill-current' : 'text-slate-700'}`} />
             ))}
          </div>
        </div>
        <div className="flex items-center gap-2 font-mono text-slate-300 bg-slate-800 px-3 py-1 rounded-lg">
          <Clock className="w-4 h-4" />
          <span className={`${timeLeft < 10 ? 'text-red-500 animate-pulse' : ''}`}>{timeLeft}s</span>
        </div>
      </div>

      {/* Progress Bar */}
      <div className="h-1 bg-slate-800 w-full">
        <div 
          className="h-full bg-gradient-to-r from-pink-500 to-purple-500 transition-all duration-1000 ease-linear"
          style={{ width: `${(timeLeft / 60) * 100}%` }}
        ></div>
      </div>

      {/* Game Area */}
      <div className="flex-1 flex flex-col items-center justify-center p-8 space-y-8 text-center">
        {gameState === 'loading' && (
          <div className="animate-bounce">
            <span className="text-6xl">🎲</span>
            <p className="mt-4 text-slate-400">Loading Puzzle...</p>
          </div>
        )}

        {puzzle && gameState !== 'loading' && (
          <>
            <div className="space-y-2">
              <span className="text-xs font-bold uppercase tracking-widest text-pink-500 bg-pink-500/10 px-3 py-1 rounded-full">
                {puzzle.category}
              </span>
              <div className="text-6xl md:text-8xl py-4 animate-pulse-slow">
                {puzzle.emojis}
              </div>
            </div>

            {gameState === 'playing' ? (
              <div className="w-full max-w-md space-y-4">
                <input
                  type="text"
                  value={guess}
                  onChange={(e) => setGuess(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && checkGuess()}
                  placeholder="Type your guess here..."
                  className="w-full bg-slate-800 border-2 border-slate-700 focus:border-pink-500 rounded-xl px-4 py-4 text-center text-xl text-white placeholder-slate-600 focus:outline-none transition-all"
                  autoFocus
                />
                <button
                  onClick={checkGuess}
                  className="w-full bg-pink-600 hover:bg-pink-700 text-white font-bold py-3 rounded-xl transition-colors"
                >
                  Submit Guess
                </button>
              </div>
            ) : (
              <div className="space-y-6 animate-fade-in-up">
                <div className="space-y-2">
                  <h3 className={`text-3xl font-bold ${gameState === 'won' ? 'text-green-400' : 'text-red-400'}`}>
                    {gameState === 'won' ? 'Correct!' : 'Time\'s Up!'}
                  </h3>
                  <p className="text-xl text-slate-300">
                    The answer was: <span className="text-white font-bold underline decoration-pink-500">{puzzle.answer}</span>
                  </p>
                </div>
                <button
                  onClick={loadPuzzle}
                  className="bg-white text-slate-900 hover:bg-slate-200 font-bold px-8 py-3 rounded-xl flex items-center gap-2 mx-auto transition-colors"
                >
                  <Play className="w-5 h-5 fill-current" />
                  Next Puzzle
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

// --- Word Wizard Challenge Sub-Component ---
const WordChallenge: React.FC<{ onExit: () => void }> = ({ onExit }) => {
  const [puzzle, setPuzzle] = useState<WordPuzzle | null>(null);
  const [options, setOptions] = useState<string[]>([]);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [gameState, setGameState] = useState<'loading' | 'playing' | 'result'>('loading');
  const [score, setScore] = useState(0);

  useEffect(() => {
    loadPuzzle();
  }, []);

  const loadPuzzle = async () => {
    setGameState('loading');
    setSelectedOption(null);
    try {
      const newPuzzle = await generateWordPuzzle();
      setPuzzle(newPuzzle);
      // Shuffle options
      const allOptions = [newPuzzle.word, ...newPuzzle.distractors].sort(() => Math.random() - 0.5);
      setOptions(allOptions);
      setGameState('playing');
    } catch (e) {
      console.error(e);
    }
  };

  const handleSelect = (option: string) => {
    if (gameState !== 'playing') return;
    setSelectedOption(option);
    setGameState('result');
    if (option === puzzle?.word) {
      setScore(s => s + 10);
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 shadow-2xl relative">
      {/* Header */}
      <div className="bg-slate-950 p-4 border-b border-slate-800 flex justify-between items-center">
        <h3 className="font-bold text-white flex items-center gap-2">
          <CaseUpper className="w-5 h-5 text-cyan-500" />
          Word Wizard
        </h3>
        <div className="flex items-center gap-2 text-cyan-400 font-bold bg-slate-900 px-3 py-1 rounded-full border border-slate-800">
          <Trophy className="w-4 h-4" />
          <span>Score: {score}</span>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex flex-col items-center justify-center p-8 space-y-10">
        {gameState === 'loading' ? (
           <div className="text-center animate-pulse">
             <div className="w-16 h-16 bg-cyan-500/20 text-cyan-500 rounded-full flex items-center justify-center mx-auto mb-4">
               <RefreshCcw className="w-8 h-8 animate-spin" />
             </div>
             <p className="text-slate-400">Summoning a tricky word...</p>
           </div>
        ) : puzzle && (
          <>
            <div className="text-center space-y-4 max-w-2xl">
              <span className="text-xs font-bold uppercase tracking-widest text-slate-500">Definition</span>
              <p className="text-2xl md:text-3xl font-medium text-white leading-relaxed">
                "{puzzle.definition}"
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 w-full max-w-3xl">
              {options.map((option, idx) => {
                let btnClass = "bg-slate-800 hover:bg-slate-700 border-slate-700 text-slate-300";
                
                if (gameState === 'result') {
                  if (option === puzzle.word) {
                    btnClass = "bg-green-600 border-green-500 text-white shadow-lg shadow-green-900/20"; // Correct answer always green
                  } else if (option === selectedOption && option !== puzzle.word) {
                    btnClass = "bg-red-600 border-red-500 text-white opacity-50"; // Wrong selection red
                  } else {
                    btnClass = "bg-slate-900 border-slate-800 text-slate-600 opacity-50"; // Others dimmed
                  }
                }

                return (
                  <button
                    key={idx}
                    onClick={() => handleSelect(option)}
                    disabled={gameState === 'result'}
                    className={`
                      relative p-6 rounded-xl border-2 text-lg font-bold transition-all duration-300
                      flex flex-col items-center justify-center gap-2
                      ${btnClass}
                      ${gameState === 'playing' ? 'hover:-translate-y-1 hover:shadow-xl' : ''}
                    `}
                  >
                    {option}
                    {gameState === 'result' && option === puzzle.word && (
                       <CheckCircle className="w-5 h-5 absolute top-3 right-3 text-white/50" />
                    )}
                    {gameState === 'result' && option === selectedOption && option !== puzzle.word && (
                       <XCircle className="w-5 h-5 absolute top-3 right-3 text-white/50" />
                    )}
                  </button>
                );
              })}
            </div>

            {gameState === 'result' && (
              <div className="animate-fade-in-up">
                 <button
                  onClick={loadPuzzle}
                  className="bg-cyan-600 hover:bg-cyan-700 text-white font-bold px-8 py-3 rounded-xl flex items-center gap-2 transition-all shadow-lg shadow-cyan-900/20"
                >
                  <Play className="w-5 h-5 fill-current" />
                  Next Word
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

// --- Two Truths Challenge Sub-Component ---
const TwoTruthsChallenge: React.FC<{ onExit: () => void }> = ({ onExit }) => {
  const [puzzle, setPuzzle] = useState<TwoTruthsPuzzle | null>(null);
  const [gameState, setGameState] = useState<'loading' | 'playing' | 'result'>('loading');
  const [score, setScore] = useState(0);
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);

  useEffect(() => {
    loadPuzzle();
  }, []);

  const loadPuzzle = async () => {
    setGameState('loading');
    setSelectedIndex(null);
    try {
      const newPuzzle = await generateTwoTruthsPuzzle();
      setPuzzle(newPuzzle);
      setGameState('playing');
    } catch (e) {
      console.error(e);
    }
  };

  const handleGuess = (index: number) => {
    if (gameState !== 'playing' || !puzzle) return;
    setSelectedIndex(index);
    setGameState('result');
    if (puzzle.statements[index].isTruth === false) {
      // The user correctly identified the lie (which is false)
      setScore(s => s + 10);
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 shadow-2xl relative">
      <div className="bg-slate-950 p-4 border-b border-slate-800 flex justify-between items-center">
        <h3 className="font-bold text-white flex items-center gap-2">
          <UserCheck className="w-5 h-5 text-rose-500" />
          Two Truths & A Lie
        </h3>
        <div className="flex items-center gap-2 text-rose-400 font-bold bg-slate-900 px-3 py-1 rounded-full border border-slate-800">
          <Trophy className="w-4 h-4" />
          <span>Score: {score}</span>
        </div>
      </div>

      <div className="flex-1 flex flex-col items-center justify-center p-8 space-y-8">
        {gameState === 'loading' ? (
           <div className="text-center animate-pulse">
             <div className="w-16 h-16 bg-rose-500/20 text-rose-500 rounded-full flex items-center justify-center mx-auto mb-4">
               <RefreshCcw className="w-8 h-8 animate-spin" />
             </div>
             <p className="text-slate-400">Fabricating truths and lies...</p>
           </div>
        ) : puzzle && (
          <>
             <div className="text-center space-y-2">
               <span className="text-xs font-bold uppercase tracking-widest text-slate-500">Topic</span>
               <h2 className="text-3xl font-bold text-white">{puzzle.topic}</h2>
               <p className="text-slate-400">Which one is the lie?</p>
             </div>

             <div className="grid grid-cols-1 gap-4 w-full max-w-2xl">
                {puzzle.statements.map((stmt, idx) => {
                   let btnClass = "bg-slate-800 hover:bg-slate-700 border-slate-700 text-slate-200";
                   
                   if (gameState === 'result') {
                     if (!stmt.isTruth) {
                        // This was the lie
                        btnClass = "bg-green-600 border-green-500 text-white"; 
                     } else if (idx === selectedIndex && stmt.isTruth) {
                        // You picked truth (wrong)
                        btnClass = "bg-red-600 border-red-500 text-white";
                     } else {
                        btnClass = "bg-slate-900 text-slate-600 border-slate-800";
                     }
                   }

                   return (
                     <button
                       key={idx}
                       onClick={() => handleGuess(idx)}
                       disabled={gameState === 'result'}
                       className={`
                         p-5 rounded-xl border text-left text-lg font-medium transition-all
                         flex items-center justify-between group
                         ${btnClass}
                         ${gameState === 'playing' ? 'hover:scale-[1.02] hover:shadow-lg' : ''}
                       `}
                     >
                       <span>{stmt.text}</span>
                       {gameState === 'result' && !stmt.isTruth && <CheckCircle className="w-5 h-5" />}
                       {gameState === 'result' && stmt.isTruth && idx === selectedIndex && <XCircle className="w-5 h-5" />}
                     </button>
                   );
                })}
             </div>

             {gameState === 'result' && (
               <div className="text-center space-y-6 animate-fade-in-up max-w-2xl">
                 <div className="bg-slate-950/50 p-4 rounded-xl border border-slate-800">
                    <p className="text-slate-300 italic">"{puzzle.explanation}"</p>
                 </div>
                 <button
                  onClick={loadPuzzle}
                  className="bg-rose-600 hover:bg-rose-700 text-white font-bold px-8 py-3 rounded-xl flex items-center gap-2 mx-auto transition-colors"
                >
                  <Play className="w-5 h-5 fill-current" />
                  Next Round
                </button>
               </div>
             )}
          </>
        )}
      </div>
    </div>
  );
};


// --- Main Games Tool ---
const GamesTool: React.FC = () => {
  const [activeGame, setActiveGame] = useState<GameMode | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [status, setStatus] = useState<LoadingState>('idle');
  const [subMode, setSubMode] = useState<'chat' | 'challenge'>('chat'); 
  
  const chatSessionRef = useRef<Chat | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const startGame = (game: GameMode) => {
    setActiveGame(game);
    setSubMode('chat'); // Reset submode
    setMessages([{ role: 'model', text: game.initialMessage }]);
    chatSessionRef.current = createChatSession(game.systemPrompt);
  };

  const exitGame = () => {
    setActiveGame(null);
    setMessages([]);
    chatSessionRef.current = null;
    setSubMode('chat');
  };

  const handleSend = async () => {
    if (!inputValue.trim() || !chatSessionRef.current || status === 'loading') return;

    const userText = inputValue.trim();
    setInputValue('');
    setStatus('loading');

    setMessages(prev => [...prev, { role: 'user', text: userText }]);

    try {
      const response = await chatSessionRef.current.sendMessage({ message: userText });
      const modelText = response.text || "The game master is silent...";
      
      setMessages(prev => [...prev, { role: 'model', text: modelText }]);
      setStatus('idle');
    } catch (error) {
      console.error("Game Error:", error);
      setStatus('error');
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  if (!activeGame) {
    return (
      <div className="max-w-4xl mx-auto space-y-8 animate-fade-in">
        <div className="text-center space-y-2">
          <h2 className="text-3xl font-bold text-white flex items-center justify-center gap-3">
            <Gamepad2 className="w-8 h-8 text-orange-500" />
            Nano Games
          </h2>
          <p className="text-slate-400">Choose your adventure and play against Gemini.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {GAMES.map((game) => (
            <button
              key={game.id}
              onClick={() => startGame(game)}
              className="bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-slate-500 p-6 rounded-2xl text-left transition-all hover:-translate-y-1 hover:shadow-xl group"
            >
              <div className={`w-12 h-12 rounded-xl bg-${game.color}-600/20 text-${game.color}-500 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                <game.icon className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-white mb-2">{game.name}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{game.description}</p>
            </button>
          ))}
        </div>
      </div>
    );
  }

  // Handle Challenge Sub-Modes
  const isChallengeMode = subMode === 'challenge';
  const showChallengeToggle = activeGame.id === 'emoji' || activeGame.id === 'word' || activeGame.id === 'truths';

  if (isChallengeMode) {
    return (
      <div className="max-w-4xl mx-auto space-y-4 h-[calc(100vh-140px)] flex flex-col animate-fade-in">
        <div className="flex items-center justify-between px-2 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-lg bg-${activeGame.color}-600/20 text-${activeGame.color}-500`}>
              <activeGame.icon className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-bold text-white">{activeGame.name}</h2>
          </div>
          <div className="flex gap-2">
             <button 
              onClick={() => setSubMode('chat')}
              className="text-slate-400 hover:text-white px-3 py-1.5 rounded-lg text-sm font-medium transition-colors border border-transparent hover:border-slate-700"
            >
              Back to Chat
            </button>
            <button 
              onClick={exitGame}
              className="text-red-400 hover:text-red-300 bg-red-500/10 hover:bg-red-500/20 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors"
            >
              Exit
            </button>
          </div>
        </div>
        {activeGame.id === 'emoji' && <EmojiChallenge onExit={() => setSubMode('chat')} />}
        {activeGame.id === 'word' && <WordChallenge onExit={() => setSubMode('chat')} />}
        {activeGame.id === 'truths' && <TwoTruthsChallenge onExit={() => setSubMode('chat')} />}
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-4 h-[calc(100vh-140px)] flex flex-col animate-fade-in">
      {/* Game Header */}
      <div className="flex items-center justify-between px-2 flex-shrink-0">
        <div className="flex items-center gap-3">
          <div className={`p-2 rounded-lg bg-${activeGame.color}-600/20 text-${activeGame.color}-500`}>
            <activeGame.icon className="w-5 h-5" />
          </div>
          <h2 className="text-xl font-bold text-white">{activeGame.name}</h2>
        </div>
        <div className="flex items-center gap-2">
          {/* Toggle for Challenge Games */}
          {showChallengeToggle && (
             <div className="flex bg-slate-800 rounded-lg p-1 mr-2 border border-slate-700">
               <button 
                 onClick={() => setSubMode('chat')}
                 className={`px-3 py-1 rounded-md text-xs font-bold transition-all ${subMode === 'chat' ? 'bg-slate-600 text-white shadow' : 'text-slate-400 hover:text-white'}`}
               >
                 Chat
               </button>
               <button 
                  onClick={() => setSubMode('challenge')}
                  className={`px-3 py-1 rounded-md text-xs font-bold transition-all flex items-center gap-1 ${subMode === 'challenge' ? `bg-${activeGame.color}-600 text-white shadow` : 'text-slate-400 hover:text-white'}`}
               >
                 <Trophy className="w-3 h-3" />
                 Challenge
               </button>
             </div>
          )}
          <button 
            onClick={exitGame}
            className="text-slate-400 hover:text-white hover:bg-slate-800 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors"
          >
            Exit Game
          </button>
        </div>
      </div>

      {/* Chat Area */}
      <div className="flex-1 bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden flex flex-col shadow-2xl relative">
        <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar">
          {messages.map((msg, idx) => (
            <div 
              key={idx} 
              className={`flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}
            >
              <div className={`
                w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0
                ${msg.role === 'user' ? 'bg-amber-500' : `bg-${activeGame.color}-600`}
              `}>
                {msg.role === 'user' ? <User className="w-5 h-5 text-slate-900" /> : <Bot className="w-5 h-5 text-white" />}
              </div>
              
              <div className={`
                max-w-[80%] rounded-2xl px-5 py-3 text-sm leading-relaxed whitespace-pre-wrap
                ${msg.role === 'user' 
                  ? 'bg-slate-800 text-slate-100 rounded-tr-none' 
                  : 'bg-slate-950/80 border border-slate-800 text-slate-300 rounded-tl-none'}
              `}>
                {msg.text}
              </div>
            </div>
          ))}
          {status === 'loading' && (
             <div className="flex gap-4">
               <div className={`w-8 h-8 rounded-full bg-${activeGame.color}-600 flex items-center justify-center flex-shrink-0`}>
                 <Bot className="w-5 h-5 text-white" />
               </div>
               <div className="bg-slate-950/50 border border-slate-800 rounded-2xl rounded-tl-none px-5 py-4 flex items-center gap-2">
                 <div className="w-2 h-2 bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                 <div className="w-2 h-2 bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                 <div className="w-2 h-2 bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
               </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex gap-3 items-end">
          <button 
            onClick={() => startGame(activeGame)} // Restart
            className="p-3 text-slate-500 hover:text-white hover:bg-slate-900 rounded-xl transition-colors mb-[2px]"
            title="Restart Game"
          >
            <RefreshCcw className="w-5 h-5" />
          </button>
          
          <div className="flex-1">
            <textarea
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Your move..."
              className={`w-full bg-slate-900 border border-slate-700 rounded-xl pl-4 pr-4 py-3 text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-${activeGame.color}-500 resize-none max-h-32 min-h-[50px] custom-scrollbar`}
              style={{ height: '52px' }}
            />
          </div>
          
          <button
            onClick={handleSend}
            disabled={!inputValue.trim() || status === 'loading'}
            className={`bg-${activeGame.color}-600 hover:bg-${activeGame.color}-700 disabled:opacity-50 disabled:cursor-not-allowed text-white p-3 rounded-xl transition-colors mb-[2px]`}
          >
            <Send className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default GamesTool;