
import React, { useState } from 'react';
import { CalendarCheck, Mail, Clock, Calendar, Users, Download, Send } from 'lucide-react';

const MeetingBooker: React.FC = () => {
  const [title, setTitle] = useState('');
  const [date, setDate] = useState('');
  const [time, setTime] = useState('');
  const [duration, setDuration] = useState('30');
  const [attendees, setAttendees] = useState('');
  const [description, setDescription] = useState('');

  const generateICS = () => {
    // Basic ICS formatting
    const startTime = new Date(`${date}T${time}`);
    const endTime = new Date(startTime.getTime() + parseInt(duration) * 60000);
    
    const formatDate = (d: Date) => d.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
    
    const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//NanoBanana//MeetingBooker//EN
BEGIN:VEVENT
UID:${Date.now()}@digitalgentry.ai
DTSTAMP:${formatDate(new Date())}
DTSTART:${formatDate(startTime)}
DTEND:${formatDate(endTime)}
SUMMARY:${title}
DESCRIPTION:${description}
ATTENDEE;RSVP=TRUE:mailto:${attendees}
END:VEVENT
END:VCALENDAR`;

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `meeting_invite.ics`;
    link.click();
  };

  const handleSendInvite = () => {
    const subject = `Meeting Invitation: ${title}`;
    const body = `Hi,\n\nI'd like to book a meeting.\n\nTopic: ${title}\nDate: ${date}\nTime: ${time}\nDuration: ${duration} minutes\n\nAgenda:\n${description}\n\nPlease reply to confirm.\n\n(Generated by AI Meet)`;
    
    window.location.href = `mailto:${attendees}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div className="max-w-2xl mx-auto space-y-8 animate-fade-in">
      <div className="text-center space-y-2">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-white flex items-center justify-center gap-3">
          <CalendarCheck className="w-8 h-8 text-cyan-500" />
          AI Meet
        </h2>
        <p className="text-slate-600 dark:text-slate-400">Secure, client-side meeting booking. Zero data stored.</p>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-xl space-y-6">
         <div className="space-y-4">
            <div>
               <label className="text-xs font-bold text-slate-500 uppercase">Meeting Title</label>
               <input 
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
                  placeholder="e.g. Project Sync"
               />
            </div>
            
            <div className="grid grid-cols-2 gap-4">
               <div>
                  <label className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1"><Calendar className="w-3 h-3"/> Date</label>
                  <input 
                     type="date"
                     value={date}
                     onChange={(e) => setDate(e.target.value)}
                     className="w-full bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
                  />
               </div>
               <div>
                  <label className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1"><Clock className="w-3 h-3"/> Time</label>
                  <input 
                     type="time"
                     value={time}
                     onChange={(e) => setTime(e.target.value)}
                     className="w-full bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
                  />
               </div>
            </div>

            <div>
               <label className="text-xs font-bold text-slate-500 uppercase">Duration (Minutes)</label>
               <select 
                  value={duration}
                  onChange={(e) => setDuration(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
               >
                  <option value="15">15 Minutes</option>
                  <option value="30">30 Minutes</option>
                  <option value="45">45 Minutes</option>
                  <option value="60">1 Hour</option>
               </select>
            </div>

            <div>
               <label className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1"><Users className="w-3 h-3"/> Attendees (Emails)</label>
               <input 
                  value={attendees}
                  onChange={(e) => setAttendees(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
                  placeholder="email@example.com, another@example.com"
               />
            </div>

            <div>
               <label className="text-xs font-bold text-slate-500 uppercase">Description / Agenda</label>
               <textarea 
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 h-24 resize-none"
                  placeholder="Meeting details..."
               />
            </div>
         </div>

         <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4">
            <button
               onClick={handleSendInvite}
               disabled={!title || !date || !time || !attendees}
               className="bg-cyan-600 hover:bg-cyan-700 disabled:opacity-50 text-white font-bold py-3 rounded-xl flex items-center justify-center gap-2 transition-all"
            >
               <Send className="w-5 h-5" /> Send Invite (Email)
            </button>
            <button
               onClick={generateICS}
               disabled={!title || !date || !time}
               className="bg-slate-800 hover:bg-slate-700 disabled:opacity-50 text-white font-bold py-3 rounded-xl flex items-center justify-center gap-2 transition-all border border-slate-700"
            >
               <Download className="w-5 h-5" /> Download .ICS
            </button>
         </div>
         <p className="text-center text-xs text-slate-500">
            Clicking "Send Invite" opens your default email client. No data is sent to our servers.
         </p>
      </div>
    </div>
  );
};

export default MeetingBooker;
