
import React from 'react';
import { X, FileText, Gavel, AlertTriangle, Scale } from 'lucide-react';

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-fade-in">
      <div className="bg-slate-900 border border-slate-800 w-full max-w-2xl rounded-3xl shadow-2xl overflow-hidden relative flex flex-col max-h-[85vh]">
        
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex justify-between items-center bg-slate-950">
          <div>
            <h3 className="text-2xl font-black text-white flex items-center gap-2 uppercase tracking-tight">
              Terms of Engagement
            </h3>
            <p className="text-slate-400 text-sm">Rules for operating within the Digital Gentry AI Suite.</p>
          </div>
          <button onClick={onClose} className="text-slate-500 hover:text-white transition-colors p-2 hover:bg-slate-800 rounded-full">
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="p-8 overflow-y-auto custom-scrollbar space-y-8 bg-slate-900/50">
          <section className="space-y-3">
            <h4 className="text-amber-500 font-bold flex items-center gap-2 uppercase text-xs tracking-widest">
              <Gavel className="w-4 h-4" /> License Grant
            </h4>
            <p className="text-slate-300 text-sm leading-relaxed font-medium">
              Access to the Digital Gentry AI Suite is granted on a per-seat basis. One license/account allows for usage on up to three personal devices. Redistribution of account credentials or "API-wrapping" our services for resale is strictly prohibited and will result in permanent termination of access without refund.
            </p>
          </section>

          <section className="space-y-3">
            <h4 className="text-amber-500 font-bold flex items-center gap-2 uppercase text-xs tracking-widest">
              <Scale className="w-4 h-4" /> Acceptable Use
            </h4>
            <p className="text-slate-300 text-sm leading-relaxed font-medium">
              Users are prohibited from generating content that promotes illegal activities, depicts extreme violence, or involves non-consensual imagery. Digital Gentry AI enforces safety filters at the model level; attempts to bypass these filters may result in account suspension.
            </p>
          </section>

          <section className="space-y-3">
            <h4 className="text-amber-500 font-bold flex items-center gap-2 uppercase text-xs tracking-widest">
              <AlertTriangle className="w-4 h-4" /> AI Disclaimer
            </h4>
            <p className="text-slate-300 text-sm leading-relaxed font-medium">
              The platform provides probabilistic outputs generated by Large Language Models. Digital Gentry AI makes no warranties regarding the factual accuracy, legal copyright status, or professional suitability of the content generated. AI outputs should be independently verified.
            </p>
          </section>
        </div>

        <div className="p-4 bg-slate-950 border-t border-slate-800 text-center">
           <p className="text-[10px] text-slate-600 font-bold uppercase tracking-widest italic">Digital Gentry Governance Framework v3.1</p>
        </div>
      </div>
    </div>
  );
};

export default TermsModal;
